# Malnati/pr-comment@v7.0.0
name: "PR Comment Template"
description: "Posta comentários padronizados e 'Sticky' em Pull Requests. Arquitetura modular v7."
author: "Ricardo Malnati"

branding:
  icon: "message-circle"
  color: "purple"

inputs:
  token:
    description: "GitHub token."
    required: true
  pr_number:
    description: "PR number."
    required: true
  # Template
  template_path:
    description: "Caminho para arquivo de template Markdown."
    required: false
    default: ""
  template_string:
    description: "Conteúdo do template Markdown (String direta). Tem prioridade sobre path."
    required: false
    default: ""
  
  # Sticky Mode
  message_id:
    description: "ID único (invisível) para atualizar o mesmo comentário."
    required: false
    default: ""
  
  # Variáveis de Substituição (Padrão)
  header_title:
    description: "Título do comentário."
    required: false
    default: ""
  header_subject:
    description: "Assunto/Subtítulo."
    required: false
    default: ""
  header_actor:
    description: "Autor da ação (ex: github-actions[bot])."
    required: false
    default: ""
  body_message:
    description: "Corpo principal da mensagem."
    required: false
    default: ""
  footer_result:
    description: "Resultado (ex: ✅ Sucesso)."
    required: false
    default: ""
  footer_advise:
    description: "Conselho/Próximo passo."
    required: false
    default: ""
  # Variáveis Extras (JSON)
  variables:
    description: "JSON string com variáveis extras para substituição no template."
    required: false
    default: "{}"

runs:
  using: "composite"
  steps:
    # ==================================================================
    # BLOCK 1: SETUP & VALIDATION
    # ==================================================================
    - id: validate_inputs
      shell: bash
      env:
        TOKEN: ${{ inputs.token }}
        PR_NUM: ${{ inputs.pr_number }}
      run: |
        echo "::group::🔧 Setup: Validation"
        if [ -z "$TOKEN" ]; then echo "❌ Token missing."; exit 1; fi
        if [ -z "$PR_NUM" ]; then echo "❌ PR Number missing."; exit 1; fi
        echo "✅ Inputs Validated."
        echo "::endgroup::"

    - id: check_perms
      shell: bash
      env:
        TOKEN: ${{ inputs.token }}
        REPO: ${{ github.repository }}
        PR_NUM: ${{ inputs.pr_number }}
      run: |
        echo "::group::🔐 Setup: Permissions Probe"
        # Teste rápido de escrita (Tenta pegar a PR para ver se tem acesso)
        # Usamos endpoint de comments com POST dummy ou GET para validar escopo
        URL="https://api.github.com/repos/$REPO/issues/$PR_NUM/comments"
        HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: Bearer $TOKEN" "$URL")
        
        if [ "$HTTP_CODE" == "200" ] || [ "$HTTP_CODE" == "404" ]; then
             echo "✅ API Access OK."
        else
             echo "⚠️ API Access Warning (HTTP $HTTP_CODE). Check 'pull-requests: write'."
        fi
        echo "::endgroup::"

    # ==================================================================
    # BLOCK 2: TEMPLATE ENGINE
    # ==================================================================
    
    # 2.0 - Resolução da Fonte do Template
    - id: resolve_template
      shell: bash
      env:
        TPL_PATH: ${{ inputs.template_path }}
        TPL_STR: ${{ inputs.template_string }}
        DEFAULT_PATH: ${{ github.action_path }}/templates/pr-comment.md
      run: |
        echo "::group::📝 Template: Resolution"
        TPL_FILE="/tmp/raw_template.md"
        
        if [ -n "$TPL_STR" ]; then
           echo "🔹 Using provided template string."
           echo "$TPL_STR" > "$TPL_FILE"
        elif [[ -n "$TPL_PATH" && -f "$TPL_PATH" ]]; then
           echo "🔹 Using custom template file: $TPL_PATH"
           cp "$TPL_PATH" "$TPL_FILE"
        else
           echo "🔹 Using default built-in template."
           cp "$DEFAULT_PATH" "$TPL_FILE"
        fi
        
        echo "template_file=$TPL_FILE" >> "$GITHUB_OUTPUT"
        echo "::endgroup::"

    # 2.1 - Renderização (Substituição de Variáveis)
    - id: render_template
      shell: bash
      env:
        TEMPLATE_FILE: ${{ steps.resolve_template.outputs.template_file }}
        # Standard Vars
        TITLE: ${{ inputs.header_title }}
        SUBJECT: ${{ inputs.header_subject }}
        ACTOR: ${{ inputs.header_actor }}
        BODY_MESSAGE: ${{ inputs.body_message }}
        FOOTER_RESULT: ${{ inputs.footer_result }}
        FOOTER_ADVISE: ${{ inputs.footer_advise }}
        # Extra Vars
        MSG_ID: ${{ inputs.message_id }}
      run: |
        echo "::group::🎨 Template: Rendering"
        
        FINAL_FILE="/tmp/final_comment.md"
        
        # 1. Injeta ID Oculto (Sticky Mode) no topo, se existir
        if [ -n "$MSG_ID" ]; then
           echo "" > "$FINAL_FILE"
        else
           echo "" > "$FINAL_FILE"
        fi
        
        # 2. Processa Envsubst (Standard Vars)
        # Note: envsubst só substitui o que está exportado
        export TITLE SUBJECT ACTOR BODY_MESSAGE FOOTER_RESULT FOOTER_ADVISE
        
        envsubst < "$TEMPLATE_FILE" >> "$FINAL_FILE"
        
        echo "✅ Render complete."
        echo "final_file=$FINAL_FILE" >> "$GITHUB_OUTPUT"
        echo "::endgroup::"

    # ==================================================================
    # BLOCK 3: COMMENT MANAGEMENT (STICKY LOGIC)
    # ==================================================================

    # 3.0 - Busca de Comentário Existente
    - id: find_comment
      if: inputs.message_id != ''
      shell: bash
      env:
        TOKEN: ${{ inputs.token }}
        REPO: ${{ github.repository }}
        PR_NUM: ${{ inputs.pr_number }}
        MSG_ID: ${{ inputs.message_id }}
      run: |
        echo "::group::🕵️ Sticky Mode: Searching"
        
        # Busca os primeiros 100 comentários
        # Filtra usando jq para achar a string ""
        SEARCH=""
        
        COMMENT_ID=$(curl -s -H "Authorization: Bearer $TOKEN" \
          "https://api.github.com/repos/$REPO/issues/$PR_NUM/comments?per_page=100" \
          | jq -r ".[] | select(.body | contains(\"$SEARCH\")) | .id" | head -n 1)
        
        if [ -n "$COMMENT_ID" ] && [ "$COMMENT_ID" != "null" ]; then
           echo "✅ Found existing comment ID: $COMMENT_ID"
           echo "action=UPDATE" >> "$GITHUB_OUTPUT"
           echo "comment_id=$COMMENT_ID" >> "$GITHUB_OUTPUT"
        else
           echo "⚪ No existing comment found. Creating new."
           echo "action=CREATE" >> "$GITHUB_OUTPUT"
        fi
        echo "::endgroup::"

    # 3.1 - Definição da URL de Destino
    - id: target_setup
      shell: bash
      env:
        REPO: ${{ github.repository }}
        PR_NUM: ${{ inputs.pr_number }}
        ACTION: ${{ steps.find_comment.outputs.action }}
        COMMENT_ID: ${{ steps.find_comment.outputs.comment_id }}
      run: |
        if [ "$ACTION" == "UPDATE" ]; then
           URL="https://api.github.com/repos/$REPO/issues/comments/$COMMENT_ID"
           METHOD="PATCH"
        else
           URL="https://api.github.com/repos/$REPO/issues/$PR_NUM/comments"
           METHOD="POST"
        fi
        echo "url=$URL" >> "$GITHUB_OUTPUT"
        echo "method=$METHOD" >> "$GITHUB_OUTPUT"

    # ==================================================================
    # BLOCK 4: API EXECUTION
    # ==================================================================

    # 4.0 - Payload JSON
    - id: prepare_payload
      shell: bash
      env:
        FILE: ${{ steps.render_template.outputs.final_file }}
      run: |
        jq --raw-input --slurp '{body: .}' "$FILE" > /tmp/payload.json

    # 4.1 - Request
    - id: send_request
      shell: bash
      env:
        TOKEN: ${{ inputs.token }}
        URL: ${{ steps.target_setup.outputs.url }}
        METHOD: ${{ steps.target_setup.outputs.method }}
      run: |
        echo "::group::📡 API: Sending Comment ($METHOD)"
        
        HTTP_CODE=$(curl -sS -w "%{http_code}" -o response.json \
          -H "Authorization: Bearer $TOKEN" \
          -H "Accept: application/vnd.github+json" \
          -H "Content-Type: application/json" \
          -X "$METHOD" "$URL" \
          -d @/tmp/payload.json)

        if [[ "$HTTP_CODE" -lt 200 || "$HTTP_CODE" -ge 300 ]]; then
          echo "❌ Request Failed ($HTTP_CODE)"
          cat response.json
          exit 1
        else
          echo "✅ Success ($HTTP_CODE)"
        fi
        echo "::endgroup::"
