# Malnati/pr-comment@v8.0.0
name: "PR Comment Pro"
description: "Posta comentários padronizados e 'Sticky' em Pull Requests com ou sem template. Malnati/pr-comment@v8.0.0"
author: "Ricardo Malnati"

branding:
  icon: "message-circle"
  color: "purple"

inputs:
  token:
    description: "GitHub token (contents:read, pull-requests:write)."
    required: true
  pr_number:
    description: "Pull Request number."
    required: true
  
  template_path:
    description: "Caminho relativo para o arquivo de template Markdown."
    required: false
    default: ""

  use_raw_body:
    description: "Se 'true', ignora templates e usa o texto cru da variável de ambiente BODY_MESSAGE."
    required: false
    default: "false"
  
  message_id:
    description: "ID único (invisível) para atualizar o mesmo comentário (Sticky Mode)."
    required: false
    default: ""

runs:
  using: "composite"
  steps:
  
    # ==================================================================
    # BLOCK 1: SETUP & VALIDATION
    # ==================================================================
    # 1.0 - Validação de Inputs Básicos
    - id: validate_inputs
      shell: bash
      env:
        TOKEN: ${{ inputs.token }}
        PR_NUM: ${{ inputs.pr_number }}
        USE_RAW_BODY: ${{ inputs.use_raw_body }}
        TEMPLATE_PATH: ${{ inputs.template_path }}
        BODY_MESSAGE: ${{ env.BODY_MESSAGE }}
      run: |
        echo "::group::🔧 Setup: Input Validation"
        if [ -z "$TOKEN" ]; then 
           echo "❌ Error: Token is missing."
           exit 1
        fi
        if [ -z "$PR_NUM" ]; then 
           echo "❌ Error: PR Number is missing."
           exit 1
        fi
        if [ "$USE_RAW_BODY" = "true" ]; then
           if [ -z "$BODY_MESSAGE" ]; then
             echo "❌ Error: use_raw_body=true, mas a variável de ambiente BODY_MESSAGE está vazia ou não foi definida."
             exit 1
           fi
           echo "::warning::Flag 'use_raw_body' habilitada: o template será ignorado e o comentário usará apenas a variável de ambiente BODY_MESSAGE."
           if [ -n "$TEMPLATE_PATH" ]; then
             echo "::notice::Input 'template_path' informado, mas será ignorado porque use_raw_body=true. Remova a flag para usar substituições via template."
           fi
        fi
        if [ -n "$TEMPLATE_PATH" ] && [ -f "$TEMPLATE_PATH" ]; then
          VARS_IN_TEMPLATE=$(grep -o '\${[A-Za-z_][A-Za-z0-9_]*}' "$TEMPLATE_PATH" | sed 's/[${}]//g' | sort -u | tr '\n' ' ')
          echo "::warning::Template com variáveis para envsubst detectado."
          echo "────────────────────────────────────────────────────────────"
          echo "Para passar variáveis para a Action, use algo semelhante a:"
          echo ""
          echo "  variables: |"
          echo "            {"
          echo "              \"VAR1\": \"...\""
          echo "            }"
          echo ""
          if [ -n "$VARS_IN_TEMPLATE" ]; then
            echo "Variáveis presentes: $VARS_IN_TEMPLATE"
          else
            echo "Nenhuma variável \${VAR} detectada no template informado."
          fi
          echo "────────────────────────────────────────────────────────────"
        fi
        echo "✅ Inputs validated."
        echo "::endgroup::"
        
    # 1.1 - Verificação de Permissões (Probe)
    - id: check_perms
      shell: bash
      env:
        TOKEN: ${{ inputs.token }}
        REPO: ${{ github.repository }}
        PR_NUM: ${{ inputs.pr_number }}
      run: |
        echo "::group::🔐 Setup: Permissions Probe"
        # Testa acesso de escrita (GET em endpoint de comments valida escopo)
        URL="https://api.github.com/repos/$REPO/issues/$PR_NUM/comments"
        echo "📡 Probing API: $URL"
        HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: Bearer $TOKEN" "$URL")
        if [ "$HTTP_CODE" == "200" ] || [ "$HTTP_CODE" == "404" ]; then
             echo "✅ API Access OK (HTTP $HTTP_CODE)."
        else
             echo "⚠️ API Access Warning (HTTP $HTTP_CODE)."
             echo "   Ensure the token has 'pull-requests: write'."
        fi
        echo "::endgroup::"

    # ==================================================================
    # BLOCK 2: TEMPLATE ENGINE (FILE BASED)
    # ==================================================================
    # 2.0 - Resolução do Arquivo de Template
    - id: resolve_template
      shell: bash
      env:
        CUSTOM_PATH: ${{ inputs.template_path }}
        DEFAULT_PATH: ${{ github.action_path }}/templates/pr-comment.md
        USE_RAW_BODY: ${{ inputs.use_raw_body }}
      run: |
        echo "::group::📝 Template: Resolution"
        TARGET_FILE="/tmp/raw_template.md"
        if [ "$USE_RAW_BODY" = "true" ]; then
           echo "🔹 Raw mode ativo: ignorando templates e usando BODY_MESSAGE como corpo do comentário.";
           : > "$TARGET_FILE"
        else
           if [[ -n "$CUSTOM_PATH" && -f "$CUSTOM_PATH" ]]; then
              echo "🔹 Selected: Custom Template ($CUSTOM_PATH)"
              cp "$CUSTOM_PATH" "$TARGET_FILE"
           else
              echo "🔹 Selected: Default Template"
              if [ ! -f "$DEFAULT_PATH" ]; then
                 echo "❌ Critical: Default template missing at $DEFAULT_PATH"
                 exit 1
              fi
              cp "$DEFAULT_PATH" "$TARGET_FILE"
           fi
        fi
        echo "template_file=$TARGET_FILE" >> "$GITHUB_OUTPUT"
        echo "::endgroup::"

    # 2.1 - Renderização e Injeção de ID
    - id: render_template
      shell: bash
      env:
        TEMPLATE_FILE: ${{ steps.resolve_template.outputs.template_file }}
        MSG_ID: ${{ inputs.message_id }}
        USE_RAW_BODY: ${{ inputs.use_raw_body }}
      run: |
        echo "::group::🎨 Template: Rendering"
        FINAL_FILE="/tmp/final_comment.md"
        if [ -n "$MSG_ID" ]; then
           echo "<!-- pr-comment-id:$MSG_ID -->" > "$FINAL_FILE"
           echo "✅ Sticky ID injected: $MSG_ID"
        else
           : > "$FINAL_FILE"
        fi
        if [ "$USE_RAW_BODY" = "true" ]; then
           echo "ℹ️ Raw mode habilitado: usando BODY_MESSAGE como corpo completo do comentário."
           printf '%s\n' "$BODY_MESSAGE" >> "$FINAL_FILE"
           echo "✅ Raw comment rendered successfully (no template)."
           echo "final_file=$FINAL_FILE" >> "$GITHUB_OUTPUT"
           echo "::endgroup::"
           exit 0
        fi
        envsubst < "$TEMPLATE_FILE" >> "$FINAL_FILE"
        echo "✅ Markdown rendered successfully."
        echo "final_file=$FINAL_FILE" >> "$GITHUB_OUTPUT"
        echo "::endgroup::"
        
    # ==================================================================
    # BLOCK 3: COMMENT MANAGEMENT (STICKY LOGIC)
    # ==================================================================
    # 3.0 - Busca de Comentário Existente
    - id: find_comment
      if: inputs.message_id != ''
      shell: bash
      env:
        TOKEN: ${{ inputs.token }}
        REPO: ${{ github.repository }}
        PR_NUM: ${{ inputs.pr_number }}
        MSG_ID: ${{ inputs.message_id }}
      run: |
        echo "::group::🕵️ Sticky Mode: Searching"
        SEARCH_STRING="pr-comment-id:$MSG_ID"
        API_URL="https://api.github.com/repos/$REPO/issues/$PR_NUM/comments?per_page=100"
        echo "🔍 Searching for ID in PR comments..."
        COMMENT_ID=$(curl -s -H "Authorization: Bearer $TOKEN" "$API_URL" \
          | jq -r ".[] | select(.body | contains(\"$SEARCH_STRING\")) | .id" \
          | head -n 1)
        if [ -n "$COMMENT_ID" ] && [ "$COMMENT_ID" != "null" ]; then
           echo "✅ Found existing comment ID: $COMMENT_ID"
           echo "action=UPDATE" >> "$GITHUB_OUTPUT"
           echo "comment_id=$COMMENT_ID" >> "$GITHUB_OUTPUT"
        else
           echo "⚪ No match found. Creating new."
           echo "action=CREATE" >> "$GITHUB_OUTPUT"
        fi
        echo "::endgroup::"

    # 3.1 - Definição da URL de Destino
    - id: target_setup
      shell: bash
      env:
        REPO: ${{ github.repository }}
        PR_NUM: ${{ inputs.pr_number }}
        ACTION: ${{ steps.find_comment.outputs.action }}
        COMMENT_ID: ${{ steps.find_comment.outputs.comment_id }}
      run: |
        # Define URL e Método baseado na busca anterior
        if [ "$ACTION" == "UPDATE" ]; then
           URL="https://api.github.com/repos/$REPO/issues/comments/$COMMENT_ID"
           METHOD="PATCH"
        else
           URL="https://api.github.com/repos/$REPO/issues/$PR_NUM/comments"
           METHOD="POST"
        fi
        echo "url=$URL" >> "$GITHUB_OUTPUT"
        echo "method=$METHOD" >> "$GITHUB_OUTPUT"

    # ==================================================================
    # BLOCK 4: API EXECUTION
    # ==================================================================
    # 4.0 - Preparação do Payload
    - id: prepare_payload
      shell: bash
      env:
        FILE: ${{ steps.render_template.outputs.final_file }}
      run: |
        echo "::group::📦 Payload: Packaging"
        # Converte o arquivo Markdown renderizado para JSON field 'body'
        jq --raw-input --slurp '{body: .}' "$FILE" > /tmp/payload.json
        echo "✅ Payload created at /tmp/payload.json"
        echo "::endgroup::"

    # 4.1 - Envio da Requisição
    - id: send_request
      shell: bash
      env:
        TOKEN: ${{ inputs.token }}
        URL: ${{ steps.target_setup.outputs.url }}
        METHOD: ${{ steps.target_setup.outputs.method }}
      run: |
        echo "::group::📡 API: Sending Comment"
        echo "Method: $METHOD"
        echo "Target: $URL"
        HTTP_CODE=$(curl -sS -w "%{http_code}" -o response.json \
          -H "Authorization: Bearer $TOKEN" \
          -H "Accept: application/vnd.github+json" \
          -H "Content-Type: application/json" \
          -X "$METHOD" "$URL" \
          -d @/tmp/payload.json)
        if [[ "$HTTP_CODE" -lt 200 || "$HTTP_CODE" -ge 300 ]]; then
          echo "❌ Request Failed ($HTTP_CODE)"
          cat response.json
          exit 1
        else
          echo "✅ Success ($HTTP_CODE)"
        fi
        echo "::endgroup::"
