# action.yml
name: "pr-comment"
description: "Publica comentários padronizados em Pull Requests (header/body/footer)."

inputs:
  token:
    description: "GitHub token (ex.: secrets.GITHUB_TOKEN)"
    required: true
  pr_number:
    description: "Número da Pull Request a ser comentada"
    required: true

  header_actor:
    description: "Autor da mensagem (ex.: github.actor)"
    required: true
  header_title:
    description: "Título da mensagem"
    required: true
  header_subject:
    description: "Assunto da mensagem"
    required: true

  body_message:
    description: "Texto principal da mensagem"
    required: true
  body_scope:
    description: "Escopo (lista/bullets)"
    required: false
    default: ""
  body_todo:
    description: "Ações pendentes / TODO"
    required: false
    default: ""

  footer_result:
    description: "Resumo do resultado"
    required: false
    default: ""
  footer_advise:
    description: "Orientação / próximos passos"
    required: false
    default: ""

outputs:
  comment_body:
    description: "Corpo final do comentário em Markdown"
    value: ${{ steps.build-message.outputs.comment_body }}

runs:
  using: "composite"
  steps:
    - id: build-message
      shell: bash
      env:
        ACTOR: ${{ inputs.header_actor }}
        TITLE: ${{ inputs.header_title }}
        SUBJECT: ${{ inputs.header_subject }}
        BODY_MESSAGE: ${{ inputs.body_message }}
        BODY_SCOPE: ${{ inputs.body_scope }}
        BODY_TODO: ${{ inputs.body_todo }}
        FOOTER_RESULT: ${{ inputs.footer_result }}
        FOOTER_ADVISE: ${{ inputs.footer_advise }}
        GITHUB_ACTION_PATH: ${{ github.action_path }}
      run: |
        set -euo pipefail

        BODY_SCOPE_BLOCK=""
        if [ -n "${BODY_SCOPE}" ]; then
          BODY_SCOPE_BLOCK="**Escopo:**\n${BODY_SCOPE}\n"
        fi

        BODY_TODO_BLOCK=""
        if [ -n "${BODY_TODO}" ]; then
          BODY_TODO_BLOCK="**Ações pendentes:**\n${BODY_TODO}\n"
        fi

        FOOTER_BLOCK=""
        if [ -n "${FOOTER_RESULT}${FOOTER_ADVISE}" ]; then
          FOOTER_BLOCK="---"
          if [ -n "${FOOTER_RESULT}" ]; then
            FOOTER_BLOCK="${FOOTER_BLOCK}\nResultado: ${FOOTER_RESULT}"
          fi
          if [ -n "${FOOTER_ADVISE}" ]; then
            FOOTER_BLOCK="${FOOTER_BLOCK}\nOrientação: ${FOOTER_ADVISE}"
          fi
        fi

        export ACTOR TITLE SUBJECT BODY_MESSAGE BODY_SCOPE_BLOCK BODY_TODO_BLOCK FOOTER_BLOCK

        COMMENT_BODY="$(envsubst < "$GITHUB_ACTION_PATH/templates/pr-comment.md")"

        {
          printf 'comment_body<<EOF\n%s\nEOF\n' "$COMMENT_BODY"
        } >> "$GITHUB_OUTPUT"

    - id: post-comment
      shell: bash
      env:
        TOKEN: ${{ inputs.token }}
        REPO: ${{ github.repository }}
        PR_NUMBER: ${{ inputs.pr_number }}
        COMMENT_BODY: ${{ steps.build-message.outputs.comment_body }}
      run: |
        set -euo pipefail

        JSON_BODY="$(printf '%b' "$COMMENT_BODY" | jq -Rs '{body: .}')"

        curl -sS \
          -H "Authorization: Bearer $TOKEN" \
          -H "Accept: application/vnd.github+json" \
          -X POST "https://api.github.com/repos/$REPO/issues/$PR_NUMBER/comments" \
          -d "$JSON_BODY" || true